version: "3.8"

#SERVICES
services:
    nginx:
        container_name: nginx
        build:
            context: .
        ports:
            - "5173:80"
        volumes:
            # - ../testPage/page1:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
